### ISSUE TITLE
Various bugs to tackle:

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/Nanite-Revolution#1]
- [x] Fix the cost of the Great Archailect
- [x] Crash with building Archailects?
- [x] Fix ascension perks
- [x] Other stuff goes here

**Comment by flying-triangulum** [comment]
![stellaris_I214KBquko](https://github.com/Sunconure11/Nanite-Revolution/assets/67757309/6f27229b-3ffc-4431-a9f8-43ae3cc48cfe)
I tested with console and reproduced the bug with no other mod but Nanite Expansion and GSE that it is recommended with, in proper order (GSE then NE below it). The AP is not taken, megastructures not unlocked, no prerequisite research done. I looked through the code, and can find no flaw with it. This happened on the legacy version as well, before you took over, so it's not anything recent. I've never encountered this bug before. Shouldn't the prerequisites line block it from appearing? And why the low cost?

I'll run a test with no GSE to narrow it down fully.

Edit: Tested it with just NE in the playset, still the same. So it's something with the mod itself.

**Comment by Sunconure11** [comment]
Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.

**Comment by Sunconure11** [comment]
> ![stellaris_I214KBquko](https://private-user-images.githubusercontent.com/67757309/299430074-6f27229b-3ffc-4431-a9f8-43ae3cc48cfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTYzODMsIm5iZiI6MTcwNjQ1NjA4MywicGF0aCI6Ii82Nzc1NzMwOS8yOTk0MzAwNzQtNmYyNzIyOWItM2ZmYy00NDMxLWE5ZjgtNDNhZTNjYzQ4Y2ZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE1MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MjkwMGZjZjcwMDczYjNjNDRhMmViODVmN2IxYTUzMmI2ZTQ2YWU4MzQ5ZmJjMzU2YmI3MjZmN2JlZDBkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7udtG1URQyxfXt6atMrUmWH7or1F0fAB8ZjACSvNAyk) I tested with console and reproduced the bug with no other mod but Nanite Expansion and GSE that it is recommended with, in proper order (GSE then NE below it). The AP is not taken, megastructures not unlocked, no prerequisite research done. I looked through the code, and can find no flaw with it. This happened on the legacy version as well, before you took over, so it's not anything recent. I've never encountered this bug before. Shouldn't the prerequisites line block it from appearing? And why the low cost?
> 
> I'll run a test with no GSE to narrow it down fully.
> 
> Edit: Tested it with just NE in the playset, still the same. So it's something with the mod itself.

![C7F59A4F-CA70-4980-9414-57FD68B54D9F](https://github.com/Sunconure11/Nanite-Revolution/assets/5614902/aff8ff53-70ba-4e35-bffb-917d89b35b7b)

Can you try this out for me?

**Comment by flying-triangulum** [comment]
> Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.

Aye, I've done that two times, delete-unsubscribe-resubscribe, and the bug persists.

I've run another test launch with just the mod and vanilla, here's the error log file:
[error.log](https://github.com/Sunconure11/Nanite-Revolution/files/14076943/error.log)

Not sure how much of that has any tangible effect, but maybe it's a start.

**Comment by flying-triangulum** [comment]
> Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.

Aye, I've done that two times, delete-unsubscribe-resubscribe, and the bug persists.

I've run another test launch with just the mod and vanilla, here's the error log file:
[error.log](https://github.com/Sunconure11/Nanite-Revolution/files/14076952/error.log)

Not sure how much of that has any tangible effect, but maybe it's a start.

**Comment by Sunconure11** [comment]
> > Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.
> 
> Aye, I've done that two times, delete-unsubscribe-resubscribe, and the bug persists.
> 
> I've run another test launch with just the mod and vanilla, here's the error log file: [error.log](https://github.com/Sunconure11/Nanite-Revolution/files/14076952/error.log)
> 
> Not sure how much of that has any tangible effect, but maybe it's a start.

Could you post that error on pastebin or gist?

**Comment by Sunconure11** [comment]
I do see lines of interest…

**Comment by Sunconure11** [comment]
https://pastebin.com/dcP6wmxF

**Comment by Sunconure11** [comment]
> > Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.
> 
> Aye, I've done that two times, delete-unsubscribe-resubscribe, and the bug persists.
> 
> I've run another test launch with just the mod and vanilla, here's the error log file: [error.log](https://github.com/Sunconure11/Nanite-Revolution/files/14076952/error.log)
> 
> Not sure how much of that has any tangible effect, but maybe it's a start.

There are a lot of issues in that error. Since I’m stuck on mobile for the time being, do you know of anyone who could help?

**Comment by Sunconure11** [comment]
![74173648-4DA3-4543-8BC5-069A9FC2D3BD](https://github.com/Sunconure11/Nanite-Revolution/assets/5614902/2c11faff-c394-4f21-93ae-92ff5ed04372)

**Comment by flying-triangulum** [comment]
> > > Just as a test, could you try reinstalling the mod from the workshop by deleting the files for it? I remember I had accidentally uploaded a broken build before fixing it.
> > 
> > 
> > Aye, I've done that two times, delete-unsubscribe-resubscribe, and the bug persists.
> > I've run another test launch with just the mod and vanilla, here's the error log file: [error.log](https://github.com/Sunconure11/Nanite-Revolution/files/14076952/error.log)
> > Not sure how much of that has any tangible effect, but maybe it's a start.
> 
> There are a lot of issues in that error. Since I’m stuck on mobile for the time being, do you know of anyone who could help?

Unfortunately, I don't. My own knowledge is nowhere near being able to troubleshoot an entire mod. I can at most fix localisation typos or see if lines are in different order.

**Comment by F1r3Pr1nc3** [comment]
Fixed the costs bug:  was a typo. I also reduced the costs and output by factor 10 (who can have 300000 alloys at once??)

**Comment by flying-triangulum** [comment]
Great to hear about the bugfix!

Regarding the cost and output, I don't think it's the right move at all. It's an artificial god - it's supposed to be a greater achievement than a Gigas matrioshka brain. And when playing with Gigas, which is recommended, that much alloys is very much expected. Not to mention rather trivial to achieve in vanilla as well, with a few Ecumenopoli.

**Comment by F1r3Pr1nc3** [comment]
Thanks for feedback and sorry, I've not that much Giga experience. But the costs were definitely too high for vanilla, as the common stock limit is 35000 alloys, so you can never built this. Then we must do the costs dynamically for Giga...

**Comment by flying-triangulum** [comment]
Ah, no, you can raise the resource cap in vanilla via several structures. Besides, this is not vanilla. This mod has techs and buildings that heavily buff resource production, including alloys. It's not meant to be vanilla. 

I believe we should not second-guess the original creator's vision; it worked the way it is set up for years for 30K+ users. The Archailect is a crowning lategame achievement that takes decades, not some Science Nexus.

**Comment by F1r3Pr1nc3** [comment]
Ok ty, then sorry for this, just half the values.

**Comment by flying-triangulum** [comment]
Hate to harp on it, but literally no one has ever complained. Except a certain guy who didn't know about resource storage, Gigastructural Engineering, or the mod itself. It will be damn annoying manually checking every update not to create extra work changing back this 'fix' no one asked for.

You did good work otherwise, though. I appreciate that a lot.
